# Generated by Django 3.0.2 on 2020-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='copy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='url',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
